"""
Traffic State Calculator
========================
Computes traffic level and congestion score from YOLO detection counts.

Design rationale:
  Instead of arbitrary hardcoded thresholds (e.g. vehicles > 40 = "high"),
  this module uses empirical percentile-based thresholds derived from
  actual detection data collected across Newcastle Urban Observatory cameras.

  The congestion score is defined as normalised occupancy following the
  fundamental traffic flow relationship (Greenshields, 1935), where density
  is approximated by detected vehicle count per camera frame:

      congestion_score = (vehicle_count / camera_capacity) * 100

  where camera_capacity is the empirically observed 95th percentile vehicle
  count for that camera, representing the practical maximum throughputf
  observable in a single frame.

  Traffic levels follow Highway Capacity Manual (HCM) Level of Service
  thresholds adapted for per-frame vehicle counts:
      - "low"    : below 25th percentile (free flow, LOS A-B)
      - "medium" : 25th to 75th percentile (stable flow, LOS C-D)
      - "high"   : above 75th percentile (approaching capacity, LOS E-F)

References:
  [1] B. Greenshields, "A study of traffic capacity," Highway Research
      Board Proceedings, vol. 14, pp. 448-477, 1935.
  [2] Transportation Research Board, "Highway Capacity Manual," 6th ed.,
      National Academies Press, Washington, DC, 2016.

Author: Sumit Malviya (W24041293)
"""

import json
import os
from pathlib import Path
from typing import Optional


# Path to pre-computed camera statistics
CAMERA_STATS_PATH = Path("data/results/camera_percentiles.json")

# Global percentile defaults (computed from full dataset if per-camera unavailable)
# These are updated by compute_percentiles() from real detection data
DEFAULT_PERCENTILES = {
    "p25_vehicles": 1,
    "p75_vehicles": 5,
    "p95_vehicles": 10,
    "p25_pedestrians": 0,
    "p75_pedestrians": 2,
    "p95_pedestrians": 5,
}

# Per-camera percentiles (loaded from JSON at startup)
_camera_percentiles = {}


def load_camera_percentiles(path: Optional[str] = None) -> dict:
    """
    Load pre-computed per-camera percentiles from JSON file.

    The JSON file is generated by compute_camera_percentiles() which
    analyses all detection records in the database to establish empirical
    thresholds for each camera location.

    Returns:
        dict mapping camera_id to percentile statistics
    """
    global _camera_percentiles

    fpath = Path(path) if path else CAMERA_STATS_PATH
    if fpath.exists():
        with open(fpath) as f:
            _camera_percentiles = json.load(f)
        return _camera_percentiles

    return {}


def get_camera_thresholds(camera_id: str) -> dict:
    """
    Get percentile thresholds for a specific camera.

    Falls back to global defaults if camera-specific data is unavailable.
    This ensures the system works even for newly added cameras that have
    no historical detection data yet.
    """
    if camera_id in _camera_percentiles:
        return _camera_percentiles[camera_id]
    return DEFAULT_PERCENTILES


def calculate_traffic_level(
    vehicles: int,
    pedestrians: int,
    camera_id: str = ""
) -> str:
    """
    Classify traffic level using empirical percentile thresholds.

    Instead of arbitrary fixed values, the classification boundaries are
    derived from observed detection distributions per camera, following
    the HCM Level of Service framework adapted for per-frame counts:

        low    = below 25th percentile (free flow)
        medium = 25th to 75th percentile (stable flow)
        high   = above 75th percentile (congested)

    Args:
        vehicles: number of vehicles detected in current frame
        pedestrians: number of pedestrians detected in current frame
        camera_id: optional camera identifier for per-camera thresholds

    Returns:
        "low", "medium", or "high"
    """
    thresholds = get_camera_thresholds(camera_id)

    p25 = thresholds.get("p25_vehicles", DEFAULT_PERCENTILES["p25_vehicles"])
    p75 = thresholds.get("p75_vehicles", DEFAULT_PERCENTILES["p75_vehicles"])

    if vehicles > p75:
        return "high"
    elif vehicles > p25:
        return "medium"
    else:
        return "low"


def calculate_congestion_score(
    vehicles: int,
    pedestrians: int,
    cyclists: int,
    camera_id: str = ""
) -> float:
    """
    Compute normalised congestion score (0-100) based on occupancy proxy.

    The score approximates the volume-to-capacity ratio from fundamental
    traffic flow theory (Greenshields, 1935). Since direct density
    (vehicles/km) cannot be measured from a single CCTV frame, this study
    uses detected vehicle count as a proxy for occupancy, normalised by
    the camera's empirical capacity (95th percentile observed count):

        base_score = min(vehicle_count / p95_capacity, 1.0) * 100

    Pedestrian and cyclist presence contribute a small additional factor
    reflecting mixed-mode congestion effects, weighted by their relative
    impact on traffic flow as established in HCM shared-space guidance:

        pedestrian_factor = min(pedestrians / p95_pedestrians, 1.0) * 10
        cyclist_factor = min(cyclists / 5, 1.0) * 5

        congestion_score = min(base_score + pedestrian_factor + cyclist_factor, 100)

    Args:
        vehicles: detected vehicle count
        pedestrians: detected pedestrian count
        cyclists: detected cyclist count
        camera_id: optional camera identifier for per-camera capacity

    Returns:
        float between 0.0 and 100.0
    """
    thresholds = get_camera_thresholds(camera_id)

    # Camera capacity = 95th percentile observed vehicle count
    capacity = thresholds.get("p95_vehicles", DEFAULT_PERCENTILES["p95_vehicles"])
    ped_capacity = thresholds.get("p95_pedestrians", DEFAULT_PERCENTILES["p95_pedestrians"])

    # Prevent division by zero for cameras with no historical data
    if capacity <= 0:
        capacity = 10
    if ped_capacity <= 0:
        ped_capacity = 5

    # Normalised occupancy (primary component, 0-100)
    vehicle_score = min(vehicles / capacity, 1.0) * 100

    # Pedestrian and cyclist adjustments (secondary, up to +15 points)
    ped_score = min(pedestrians / ped_capacity, 1.0) * 10
    cyc_score = min(cyclists / 5, 1.0) * 5

    total = min(vehicle_score + ped_score + cyc_score, 100.0)
    return round(total, 2)


def compute_camera_percentiles(detections: list, output_path: Optional[str] = None) -> dict:
    """
    Compute per-camera percentile thresholds from historical detection data.

    This function should be run periodically (or once before deployment) to
    establish empirical baselines for each camera. It analyses all available
    detection records and computes the 25th, 75th, and 95th percentile
    vehicle and pedestrian counts per camera.

    Args:
        detections: list of dicts with keys: camera_id, vehicles, pedestrians
        output_path: optional path to save results as JSON

    Returns:
        dict mapping camera_id to percentile statistics

    Usage:
        # From database query results:
        percentiles = compute_camera_percentiles(detection_records)

        # Or run as a script:
        python -c "from app.services.traffic_calculator import *; ..."
    """
    import numpy as np
    from collections import defaultdict

    camera_data = defaultdict(lambda: {"vehicles": [], "pedestrians": []})

    for det in detections:
        cam = det.get("camera_id", det.get("camera", "unknown"))
        camera_data[cam]["vehicles"].append(det.get("vehicles", 0))
        camera_data[cam]["pedestrians"].append(det.get("pedestrians", 0))

    results = {}
    all_vehicles = []
    all_pedestrians = []

    for cam_id, data in camera_data.items():
        v = np.array(data["vehicles"])
        p = np.array(data["pedestrians"])
        all_vehicles.extend(data["vehicles"])
        all_pedestrians.extend(data["pedestrians"])

        results[cam_id] = {
            "n_observations": len(v),
            "p25_vehicles": float(np.percentile(v, 25)),
            "p75_vehicles": float(np.percentile(v, 75)),
            "p95_vehicles": float(np.percentile(v, 95)),
            "mean_vehicles": float(np.mean(v)),
            "p25_pedestrians": float(np.percentile(p, 25)),
            "p75_pedestrians": float(np.percentile(p, 75)),
            "p95_pedestrians": float(np.percentile(p, 95)),
            "mean_pedestrians": float(np.mean(p)),
        }

    # Also compute global defaults from all cameras combined
    if all_vehicles:
        av = np.array(all_vehicles)
        ap = np.array(all_pedestrians)
        results["__global__"] = {
            "n_observations": len(av),
            "p25_vehicles": float(np.percentile(av, 25)),
            "p75_vehicles": float(np.percentile(av, 75)),
            "p95_vehicles": float(np.percentile(av, 95)),
            "mean_vehicles": float(np.mean(av)),
            "p25_pedestrians": float(np.percentile(ap, 25)),
            "p75_pedestrians": float(np.percentile(ap, 75)),
            "p95_pedestrians": float(np.percentile(ap, 95)),
            "mean_pedestrians": float(np.mean(ap)),
        }

    # Save to JSON
    save_path = Path(output_path) if output_path else CAMERA_STATS_PATH
    save_path.parent.mkdir(parents=True, exist_ok=True)
    with open(save_path, "w") as f:
        json.dump(results, f, indent=2)

    print(f"Camera percentiles computed for {len(results) - 1} cameras")
    print(f"Saved to {save_path}")

    return results


# Load percentiles on import (if file exists)
load_camera_percentiles()